### PR TITLE
fix florence model

### PR DESCRIPTION
**Pull request by hjh0119**
# PR type
- [x] Bug Fix
- [ ] New Feature
- [ ] Document Updates
- [ ] More Models or Datasets Support

# PR information
Add length truncation for Florence models: https://github.com/modelscope/swift/issues/1267
Add the InternVL2-40B model

### CODE REVIEW

**Comment by lucasjinreal** [comment]
Hi, I think force the lenght of attention mask and input ids might not be a good way.

We need passing the training samples maybe? if the content length extremly large, it's better drop it than train on a trucated one

**Review by Jintao-Huang — APPROVED** [review]

**Comment by lucasjinreal** [comment]
Can we set max lenght to 4096?

**Comment by hjh0119** [comment]
> Can we set max lenght to 4096?

You can manually set the parameter `--max_length`, but unexpected results may occur because the model itself does not support very long lengths.

**Comment by lucasjinreal** [comment]
I found I still got same error ,when set max-length to 2048.
WHy

**Comment by lucasjinreal** [comment]
It's really can not exceed 1024, limit to 1024 then everything is OK, why???

**Pull request merged**
