### PR TITLE
Feat 1018

### PR DESCRIPTION
**Pull request by Jintao-Huang**
1. fix sh
2. dataset_split_seed -> dataset_seed
3. max_new_tokens: 1024 -> 2048 (default)

### CODE REVIEW

**Comment by Jintao-Huang** [comment]
4. add arguments: model_id_or_path, model_revision (update default: dtype), (update readme)
5. update MODEL_MAPPING: model_id -> model_id_or_path
6. update feat: acc, eval_acc

**Comment by Jintao-Huang** [comment]
7. update register_dataset
8. update baichuan2_13b_chat mp+ddp sh

**Comment by Jintao-Huang** [comment]
9. move llm example to swift
10. update register_model, register_template

**Comment by Jintao-Huang** [comment]
11. move main into swift.llm.run and add cli

**Comment by Jintao-Huang** [comment]
12. update adapter_cfg in configuration.json

**Comment by Jintao-Huang** [comment]
13. add inference stream=True/False

**Review by tastelikefeet — APPROVED** [review]

**Pull request merged**
